server.port=8081

spring.application.name=equispedia
spring.datasource.url=jdbc:postgresql://localhost:5432/equispedia
spring.datasource.username=postgres
spring.datasource.password=123momiaes
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Asegura que Spring ejecute el script de inicialización de datos
spring.sql.init.mode=always

# DIFERIR: Hace que JPA/Hibernate cree las tablas ANTES de que se ejecute el data.sql
spring.jpa.defer-datasource-initialization=true

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# Spring Mail (Envio de correos)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

