server.port=8081

spring.application.name=equispedia
spring.datasource.url=jdbc:postgresql://localhost:5432/equispedia
spring.datasource.username=postgres
spring.datasource.password=123momiaes
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Asegura que Spring ejecute el script de inicialización de datos
spring.sql.init.mode=always

# DIFERIR: Hace que JPA/Hibernate cree las tablas ANTES de que se ejecute el data.sql
spring.jpa.defer-datasource-initialization=true

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
