server.port=8081

spring.application.name=${DB_NAME:equispedia}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:15432/equispedia}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123momiaes}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Asegura que Spring ejecute el script de inicializacion de datos
spring.sql.init.mode=never

# DIFERIR: Hace que JPA/Hibernate cree las tablas ANTES de que se ejecute el data.sql
spring.jpa.defer-datasource-initialization=true

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY:your_stripe_secret_key_here}

# Actuator
management.endpoints.web.exposure.include=health

# Email SMTP Configuration (Equispedia cPanel)
spring.mail.host=mail.equispedia.online
spring.mail.port=26
spring.mail.username=no-reply@equispedia.online
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=false

# Para poder leer los logs
logging.file.name=spring-backend.log
